{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "node-life-support.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "node-life-support.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "node-life-support.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
