apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-life-support
  namespace: node-life-support
  labels:
    app.kubernetes.io/name: node-life-support
    app.kubernetes.io/component: controller
